version: "3.8"

services:
    serve:
        build:
            context: .
            dockerfile: Dockerfile.serve
        container_name: text_predictor
        ports:
            - "8000:8000"
        volumes:
            - .:/app
        command: ["poetry", "run", "uvicorn", "src.text_classification.api:app", "--host", "0.0.0.0", "--port", "8000"]
        

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
# airflow:
    #     build:
    #         context: .
    #         dockerfile: Dockerfile.airflow
    #     container_name: training_module
    #     environment:
    #         - AIRFLOW__CORE__LOAD_EXAMPLES=False
    #         - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
    #     ports:
    #         - "8080:8793"
    #     volumes:
    #         - ./airflow/dags:/opt/airflow/dags/
    #     command: bash -c "mkdir -p /opt/airflow && chmod 777 /opt/airflow && airflow db init && airflow users create --username admin --firstname admin --lastname user --role Admin --email admin@example.com --password admin && airflow webserver --port 8080 -D && airflow scheduler"
