name: CI/CD for Text Classifier

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.16
        options: --privileged
        
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.12'


    - name: Install dependencies
      run: |
        cd text_classification
        pip install poetry
        poetry install

    - name: Run Tests
      run: |
        cd text_classification
        poetry run pytest


    - name: Set up Docker Compose
      run: |
        cd text_classification
        docker --version
        docker compose --version

    - name: Build and start services
      run: |
        cd text_classification
        docker compose down
        docker compose up --build -d

    - name: Testing inside docker
      id: docker_test
      run: |
        docker exec text_predictor poetry run pytest

    - name: Redeploying the model
      if: steps.docker_test.outcome == 'success'
      run: |
        docker exec text_predictor poetry run python src/text_classification/train.py
        
    - name: Slack Notification on Failure
      if: failure()
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_MESSAGE: "❌ GitHub Action failed for ${{ github.repository }} on branch ${{ github.ref }}."    

    - name: Slack Notification on Success
      if: success()
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_MESSAGE: "✅ GitHub Action success for ${{ github.repository }} on branch ${{ github.ref }}."    
