name: CI/CD for Text Classifier

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.16
        options: --privileged
        
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.12'


    - name: Install dependencies
      run: |
        cd text_classification
        pip install poetry
        poetry install

    - name: Run Tests
      run: |
        cd text_classification
        poetry run pytest


    - name: Set up Docker Compose
      run: |
        cd text_classification
        docker --version
        docker compose --version

    - name: Build and start services
      run: |
        cd text_classification
        docker compose down
        docker compose up --build -d

    - name: Testing inside docker
      run: |
        docker exec serve poetry run test_classification/pytest


